# This file contains values from Cookiecutter

default_context:
  project_name: "specviz"
  project_description: "viz of spectra"
  organization: "specviz"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "specviz"
  email: "phzwart@lbl.gov"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
